[package]
name = "y-py"
version = "0.5.9"
rust-version = "1.58"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "y_py"
crate-type = ["cdylib"]

[dependencies]
lib0 = "0.12.2"
yrs = "0.12.2"

[dependencies.pyo3]
version = "0.16.5"
features = ["extension-module"]
